import { existsSync, readFileSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath } from "url";
import { gunzipSync } from "zlib";
import { bookNameFromNumber, bookNumberFromName, formatReference, parseReference } from "./reference-parser.js";

// Curated verse-to-verse cross-reference dataset (openbible.info, CC-BY).
// The data file is generated by `npm run fetch-xrefs` and ships as a gzipped
// TSV with numeric book ids: "45.8.28\t50.1.6\t70" (from, to[, -endCh.endV], votes).

export interface CrossReference {
  reference: string;
  votes: number;
}

interface TargetEntry {
  reference: string;
  votes: number;
}

// Index: "book.chapter" -> verse -> targets
type CrossReferenceIndex = Map<string, Map<number, TargetEntry[]>>;

const indexCache = new Map<string, CrossReferenceIndex>();

export function defaultCrossReferenceDataPath(): string {
  const here = dirname(fileURLToPath(import.meta.url));
  // src/services (or dist/services) -> package root -> data/
  return join(here, "..", "..", "data", "cross-references.tsv.gz");
}

export function isCrossReferenceDataAvailable(dataPath: string = defaultCrossReferenceDataPath()): boolean {
  return existsSync(dataPath);
}

function parseTarget(raw: string): string | null {
  // "43.1.1" or "43.1.1-1.3" (end repeats chapter.verse within the same book)
  const match = raw.match(/^(\d+)\.(\d+)\.(\d+)(?:-(\d+)\.(\d+))?$/);
  if (!match) return null;
  const book = bookNameFromNumber(parseInt(match[1], 10));
  if (!book) return null;
  return formatReference({
    book,
    chapter: parseInt(match[2], 10),
    verse: parseInt(match[3], 10),
    endChapter: match[4] ? parseInt(match[4], 10) : undefined,
    endVerse: match[5] ? parseInt(match[5], 10) : undefined,
  });
}

function loadIndex(dataPath: string): CrossReferenceIndex {
  const cached = indexCache.get(dataPath);
  if (cached) return cached;

  if (!existsSync(dataPath)) {
    throw new Error(
      `Cross-reference dataset not found at ${dataPath}. ` +
      `Run "npm run fetch-xrefs" in logos-mcp-server/ to download it (openbible.info, CC-BY).`
    );
  }

  const text = gunzipSync(readFileSync(dataPath)).toString("utf-8");
  const index: CrossReferenceIndex = new Map();

  for (const line of text.split("\n")) {
    if (!line) continue;
    const [from, to, votesRaw] = line.split("\t");
    if (!from || !to) continue;

    const fromMatch = from.match(/^(\d+)\.(\d+)\.(\d+)$/);
    if (!fromMatch) continue;
    const target = parseTarget(to);
    if (!target) continue;

    const chapterKey = `${fromMatch[1]}.${fromMatch[2]}`;
    const verse = parseInt(fromMatch[3], 10);
    const votes = parseInt(votesRaw ?? "0", 10) || 0;

    let verseMap = index.get(chapterKey);
    if (!verseMap) {
      verseMap = new Map();
      index.set(chapterKey, verseMap);
    }
    let entries = verseMap.get(verse);
    if (!entries) {
      entries = [];
      verseMap.set(verse, entries);
    }
    entries.push({ reference: target, votes });
  }

  indexCache.set(dataPath, index);
  return index;
}

/**
 * Look up curated cross-references for a passage. A chapter-only reference
 * aggregates every verse in the chapter; a verse range aggregates each verse
 * in the range. Results are deduplicated and sorted by community votes.
 */
export function findCrossReferences(
  reference: string,
  options: { limit?: number; dataPath?: string } = {}
): CrossReference[] {
  const dataPath = options.dataPath ?? defaultCrossReferenceDataPath();
  const limit = options.limit ?? 15;
  const index = loadIndex(dataPath);

  const ref = parseReference(reference);
  const bookNumber = bookNumberFromName(ref.book);
  if (bookNumber === null) return [];

  const collected: TargetEntry[] = [];

  const collectChapter = (chapter: number, fromVerse?: number, toVerse?: number) => {
    const verseMap = index.get(`${bookNumber}.${chapter}`);
    if (!verseMap) return;
    for (const [verse, entries] of verseMap) {
      if (fromVerse !== undefined && verse < fromVerse) continue;
      if (toVerse !== undefined && verse > toVerse) continue;
      collected.push(...entries);
    }
  };

  if (ref.verse === undefined) {
    // Whole chapter (or chapter range)
    const endChapter = ref.endChapter ?? ref.chapter;
    for (let c = ref.chapter; c <= endChapter; c += 1) collectChapter(c);
  } else if (ref.endChapter === undefined || ref.endChapter === ref.chapter) {
    collectChapter(ref.chapter, ref.verse, ref.endVerse ?? ref.verse);
  } else {
    collectChapter(ref.chapter, ref.verse, undefined);
    for (let c = ref.chapter + 1; c < ref.endChapter; c += 1) collectChapter(c);
    collectChapter(ref.endChapter, undefined, ref.endVerse);
  }

  // Dedupe by target, keeping the highest vote count
  const best = new Map<string, number>();
  for (const entry of collected) {
    const existing = best.get(entry.reference);
    if (existing === undefined || entry.votes > existing) {
      best.set(entry.reference, entry.votes);
    }
  }

  // Exclude targets that are the source itself
  const sourceKey = formatReference(ref);
  best.delete(sourceKey);

  return Array.from(best.entries())
    .map(([target, votes]) => ({ reference: target, votes }))
    .sort((a, b) => b.votes - a.votes || a.reference.localeCompare(b.reference))
    .slice(0, limit);
}
